// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/commands/proto/types.proto

package commands

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	scheme "github.com/jstuczyn/CoconutGo/crypto/coconut/scheme"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_OK                StatusCode = 0
	StatusCode_UNKNOWN           StatusCode = 1
	StatusCode_INVALID_COMMAND   StatusCode = 2
	StatusCode_INVALID_ARGUMENTS StatusCode = 3
	StatusCode_PROCESSING_ERROR  StatusCode = 4
	StatusCode_NOT_IMPLEMENTED   StatusCode = 5
	StatusCode_REQUEST_TIMEOUT   StatusCode = 6
	StatusCode_UNAVAILABLE       StatusCode = 7
)

var StatusCode_name = map[int32]string{
	0: "OK",
	1: "UNKNOWN",
	2: "INVALID_COMMAND",
	3: "INVALID_ARGUMENTS",
	4: "PROCESSING_ERROR",
	5: "NOT_IMPLEMENTED",
	6: "REQUEST_TIMEOUT",
	7: "UNAVAILABLE",
}

var StatusCode_value = map[string]int32{
	"OK":                0,
	"UNKNOWN":           1,
	"INVALID_COMMAND":   2,
	"INVALID_ARGUMENTS": 3,
	"PROCESSING_ERROR":  4,
	"NOT_IMPLEMENTED":   5,
	"REQUEST_TIMEOUT":   6,
	"UNAVAILABLE":       7,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed9fc3098e7f53c0, []int{0}
}

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9fc3098e7f53c0, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SignRequest struct {
	PubM                 [][]byte `protobuf:"bytes,1,rep,name=pubM,proto3" json:"pubM,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignRequest) Reset()         { *m = SignRequest{} }
func (m *SignRequest) String() string { return proto.CompactTextString(m) }
func (*SignRequest) ProtoMessage()    {}
func (*SignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9fc3098e7f53c0, []int{1}
}

func (m *SignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignRequest.Unmarshal(m, b)
}
func (m *SignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignRequest.Marshal(b, m, deterministic)
}
func (m *SignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignRequest.Merge(m, src)
}
func (m *SignRequest) XXX_Size() int {
	return xxx_messageInfo_SignRequest.Size(m)
}
func (m *SignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignRequest proto.InternalMessageInfo

func (m *SignRequest) GetPubM() [][]byte {
	if m != nil {
		return m.PubM
	}
	return nil
}

type SignResponse struct {
	Sig                  *scheme.ProtoSignature `protobuf:"bytes,1,opt,name=sig,proto3" json:"sig,omitempty"`
	Status               *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SignResponse) Reset()         { *m = SignResponse{} }
func (m *SignResponse) String() string { return proto.CompactTextString(m) }
func (*SignResponse) ProtoMessage()    {}
func (*SignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9fc3098e7f53c0, []int{2}
}

func (m *SignResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignResponse.Unmarshal(m, b)
}
func (m *SignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignResponse.Marshal(b, m, deterministic)
}
func (m *SignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignResponse.Merge(m, src)
}
func (m *SignResponse) XXX_Size() int {
	return xxx_messageInfo_SignResponse.Size(m)
}
func (m *SignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignResponse proto.InternalMessageInfo

func (m *SignResponse) GetSig() *scheme.ProtoSignature {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *SignResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type VerifyRequest struct {
	Sig                  *scheme.ProtoSignature `protobuf:"bytes,1,opt,name=sig,proto3" json:"sig,omitempty"`
	PubM                 [][]byte               `protobuf:"bytes,2,rep,name=pubM,proto3" json:"pubM,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *VerifyRequest) Reset()         { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()    {}
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9fc3098e7f53c0, []int{3}
}

func (m *VerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRequest.Unmarshal(m, b)
}
func (m *VerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRequest.Marshal(b, m, deterministic)
}
func (m *VerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRequest.Merge(m, src)
}
func (m *VerifyRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyRequest.Size(m)
}
func (m *VerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRequest proto.InternalMessageInfo

func (m *VerifyRequest) GetSig() *scheme.ProtoSignature {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *VerifyRequest) GetPubM() [][]byte {
	if m != nil {
		return m.PubM
	}
	return nil
}

func init() {
	proto.RegisterEnum("commands.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterType((*Status)(nil), "commands.Status")
	proto.RegisterType((*SignRequest)(nil), "commands.SignRequest")
	proto.RegisterType((*SignResponse)(nil), "commands.SignResponse")
	proto.RegisterType((*VerifyRequest)(nil), "commands.VerifyRequest")
}

func init() { proto.RegisterFile("server/commands/proto/types.proto", fileDescriptor_ed9fc3098e7f53c0) }

var fileDescriptor_ed9fc3098e7f53c0 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0x49, 0xbb, 0xa5, 0x70, 0x19, 0x9a, 0x31, 0x20, 0x2a, 0x9e, 0xba, 0xbe, 0x50, 0x90,
	0x88, 0xa5, 0x21, 0xf1, 0x9e, 0xb5, 0x56, 0x15, 0xad, 0x71, 0x8a, 0x93, 0x14, 0x89, 0x97, 0xaa,
	0xf5, 0x4c, 0x17, 0xa4, 0xc4, 0x21, 0x76, 0x90, 0xc2, 0x87, 0xe1, 0xb3, 0x22, 0x27, 0x8b, 0x90,
	0xe0, 0x89, 0xb7, 0xcb, 0xdd, 0xff, 0xee, 0xff, 0xbb, 0x8b, 0xe1, 0x4a, 0xcb, 0xfa, 0x87, 0xac,
	0x89, 0x50, 0x45, 0x71, 0x28, 0xef, 0x34, 0xa9, 0x6a, 0x65, 0x14, 0x31, 0x6d, 0x25, 0xb5, 0xdf,
	0xc5, 0xf8, 0xf1, 0x50, 0x7b, 0xfd, 0x46, 0xd4, 0x6d, 0x65, 0x14, 0x11, 0x4a, 0xa8, 0xb2, 0x31,
	0x44, 0x8b, 0x7b, 0x59, 0xc8, 0x7f, 0x5b, 0xe6, 0x1f, 0xc1, 0x4d, 0xcc, 0xc1, 0x34, 0x1a, 0x63,
	0x38, 0x13, 0xea, 0x4e, 0x4e, 0x9d, 0x99, 0xb3, 0x38, 0xe7, 0x5d, 0x8c, 0xa7, 0x30, 0x29, 0xa4,
	0xd6, 0x87, 0x93, 0x9c, 0x8e, 0x66, 0xce, 0xe2, 0x09, 0x1f, 0x3e, 0xe7, 0x57, 0xe0, 0x25, 0xf9,
	0xa9, 0xe4, 0xf2, 0x7b, 0x23, 0xb5, 0xb1, 0xcd, 0x55, 0x73, 0x8c, 0xa6, 0xce, 0x6c, 0xbc, 0xb8,
	0xe0, 0x5d, 0x3c, 0x17, 0x70, 0xd1, 0x4b, 0x74, 0xa5, 0x4a, 0x2d, 0xf1, 0x5b, 0x18, 0xeb, 0xfc,
	0xd4, 0xcd, 0xf7, 0xae, 0x5f, 0xf9, 0x0f, 0x68, 0xfe, 0xd6, 0x72, 0x58, 0xe1, 0xc1, 0x34, 0xb5,
	0xe4, 0x56, 0x83, 0x17, 0xe0, 0xea, 0x8e, 0xaa, 0xb3, 0xf5, 0xae, 0x91, 0x3f, 0x6c, 0xe6, 0xf7,
	0xb4, 0xfc, 0xa1, 0x3e, 0x67, 0xf0, 0x74, 0x27, 0xeb, 0xfc, 0x6b, 0x3b, 0x90, 0xfc, 0x87, 0xcb,
	0x00, 0x3d, 0xfa, 0x03, 0xfd, 0xee, 0x97, 0x03, 0xd0, 0x5b, 0x2c, 0xed, 0x01, 0x5c, 0x18, 0xc5,
	0xb7, 0xe8, 0x11, 0xf6, 0x60, 0x92, 0xb1, 0x5b, 0x16, 0x7f, 0x66, 0xc8, 0xc1, 0xcf, 0xe1, 0x32,
	0x64, 0xbb, 0x60, 0x13, 0xae, 0xf6, 0xcb, 0x38, 0x8a, 0x02, 0xb6, 0x42, 0x23, 0xfc, 0x12, 0x9e,
	0x0d, 0xc9, 0x80, 0xaf, 0xb3, 0x88, 0xb2, 0x34, 0x41, 0x63, 0xfc, 0x02, 0xd0, 0x96, 0xc7, 0x4b,
	0x9a, 0x24, 0x21, 0x5b, 0xef, 0x29, 0xe7, 0x31, 0x47, 0x67, 0x76, 0x02, 0x8b, 0xd3, 0x7d, 0x18,
	0x6d, 0x37, 0xd4, 0x2a, 0xe9, 0x0a, 0x9d, 0xdb, 0x24, 0xa7, 0x9f, 0x32, 0x9a, 0xa4, 0xfb, 0x34,
	0x8c, 0x68, 0x9c, 0xa5, 0xc8, 0xc5, 0x97, 0xe0, 0x65, 0x2c, 0xd8, 0x05, 0xe1, 0x26, 0xb8, 0xd9,
	0x50, 0x34, 0xb9, 0x21, 0x5f, 0xde, 0x9f, 0x72, 0x73, 0xdf, 0x1c, 0xed, 0x49, 0xc8, 0x37, 0x6d,
	0x1a, 0xf1, 0xb3, 0x2d, 0xc9, 0xb2, 0xdf, 0x73, 0xad, 0xc8, 0x5f, 0xcf, 0xe4, 0xe8, 0x76, 0x3f,
	0xfa, 0xc3, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x8d, 0x44, 0x28, 0x40, 0x02, 0x00, 0x00,
}
