language: go
go: 
  - "1.11"

env:
  - DEP_VERSION="0.5.0"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

before_script:
  - go get github.com/wadey/gocovmerge
  - go install $GOPATH/src/github.com/wadey/gocovmerge

script: 
  - ./changecurve.sh BLS
  - go test -v ./... -race -coverprofile=coverageBLS.out -covermode=atomic
  - ./changecurve.sh BN
  - go test -v ./... -race -coverprofile=coverageBN.out -covermode=atomic
  - $GOPATH/bin/gocovmerge coverageBLS.out coverageBN.out > coverage.txt
  - rm coverageB*
  # - go test ./... -timeout=60m -run nothing -bench=. -cpu=1,2,4 -benchtime=2s

after_success:
  - bash <(curl -s https://codecov.io/bash)

git:
  depth: 1

notifications:
  email: false