// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tendermint/nymabci/transaction/proto/types.proto

package transaction

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewAccountRequest struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Credential           []byte   `protobuf:"bytes,2,opt,name=Credential,proto3" json:"Credential,omitempty"`
	Sig                  []byte   `protobuf:"bytes,3,opt,name=Sig,proto3" json:"Sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewAccountRequest) Reset()         { *m = NewAccountRequest{} }
func (m *NewAccountRequest) String() string { return proto.CompactTextString(m) }
func (*NewAccountRequest) ProtoMessage()    {}
func (*NewAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb862c5130efc92, []int{0}
}

func (m *NewAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewAccountRequest.Unmarshal(m, b)
}
func (m *NewAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewAccountRequest.Marshal(b, m, deterministic)
}
func (m *NewAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewAccountRequest.Merge(m, src)
}
func (m *NewAccountRequest) XXX_Size() int {
	return xxx_messageInfo_NewAccountRequest.Size(m)
}
func (m *NewAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewAccountRequest proto.InternalMessageInfo

func (m *NewAccountRequest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *NewAccountRequest) GetCredential() []byte {
	if m != nil {
		return m.Credential
	}
	return nil
}

func (m *NewAccountRequest) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func init() {
	proto.RegisterType((*NewAccountRequest)(nil), "transaction.NewAccountRequest")
}

func init() {
	proto.RegisterFile("tendermint/nymabci/transaction/proto/types.proto", fileDescriptor_ffb862c5130efc92)
}

var fileDescriptor_ffb862c5130efc92 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0x31, 0x4b, 0xc5, 0x30,
	0x14, 0x46, 0xa9, 0x05, 0xc1, 0xe8, 0xa0, 0x99, 0x3a, 0x88, 0x88, 0x93, 0x53, 0x53, 0x70, 0x15,
	0x41, 0x3b, 0x38, 0x08, 0x22, 0x75, 0x73, 0x4b, 0x6e, 0x2f, 0x25, 0xd2, 0xde, 0x5b, 0x93, 0x1b,
	0x34, 0xfe, 0xfa, 0xc7, 0xcb, 0xf2, 0x3a, 0xbd, 0xed, 0x70, 0xce, 0xf2, 0x7d, 0xaa, 0x13, 0xa4,
	0x11, 0xc3, 0xe2, 0x49, 0x0c, 0xe5, 0xc5, 0x3a, 0xf0, 0x46, 0x82, 0xa5, 0x68, 0x41, 0x3c, 0x93,
	0x59, 0x03, 0x0b, 0x1b, 0xc9, 0x2b, 0xc6, 0xb6, 0xb0, 0x3e, 0xdf, 0xe4, 0x3b, 0x50, 0x57, 0xef,
	0xf8, 0xfb, 0x0c, 0xc0, 0x89, 0x64, 0xc0, 0x9f, 0x84, 0x51, 0xf4, 0xb5, 0x3a, 0xfb, 0x48, 0x6e,
	0xf6, 0xf0, 0x86, 0xb9, 0xa9, 0x6e, 0xab, 0xfb, 0x8b, 0xe1, 0x20, 0xf4, 0x8d, 0x52, 0x7d, 0xc0,
	0x11, 0x49, 0xbc, 0x9d, 0x9b, 0x93, 0x92, 0x37, 0x46, 0x5f, 0xaa, 0xfa, 0xd3, 0x4f, 0x4d, 0x5d,
	0xc2, 0x1e, 0x5f, 0x9e, 0xbe, 0x1e, 0xbb, 0x3f, 0x0b, 0xd6, 0xb5, 0x1c, 0x26, 0xf3, 0x1d, 0x25,
	0xc1, 0x7f, 0x26, 0xd3, 0x33, 0x30, 0x25, 0x79, 0x65, 0x73, 0xfc, 0x83, 0x3b, 0x2d, 0xc3, 0x1f,
	0x76, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x72, 0x9a, 0x6d, 0xec, 0x00, 0x00, 0x00,
}
