// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tendermint/nymabci/transaction/proto/types.proto

package transaction

import (
	scheme "0xacab.org/jstuczyn/CoconutGo/crypto/coconut/scheme"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewAccountRequest struct {
	// Public Key of the user used to derive account address and validate signature
	PublicKey []byte `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	// represents some optional credential from an IP if required
	Credential []byte `protobuf:"bytes,2,opt,name=Credential,proto3" json:"Credential,omitempty"`
	// Signature on request to confirm its validity + asserts knowledge of private key
	Sig                  []byte   `protobuf:"bytes,3,opt,name=Sig,proto3" json:"Sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewAccountRequest) Reset()         { *m = NewAccountRequest{} }
func (m *NewAccountRequest) String() string { return proto.CompactTextString(m) }
func (*NewAccountRequest) ProtoMessage()    {}
func (*NewAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb862c5130efc92, []int{0}
}

func (m *NewAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewAccountRequest.Unmarshal(m, b)
}
func (m *NewAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewAccountRequest.Marshal(b, m, deterministic)
}
func (m *NewAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewAccountRequest.Merge(m, src)
}
func (m *NewAccountRequest) XXX_Size() int {
	return xxx_messageInfo_NewAccountRequest.Size(m)
}
func (m *NewAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewAccountRequest proto.InternalMessageInfo

func (m *NewAccountRequest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *NewAccountRequest) GetCredential() []byte {
	if m != nil {
		return m.Credential
	}
	return nil
}

func (m *NewAccountRequest) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type AccountTransferRequest struct {
	// Used to validate signature + determine source address
	SourcePublicKey []byte `protobuf:"bytes,1,opt,name=SourcePublicKey,proto3" json:"SourcePublicKey,omitempty"`
	// Used to determine target address
	TargetPublicKey []byte `protobuf:"bytes,2,opt,name=TargetPublicKey,proto3" json:"TargetPublicKey,omitempty"`
	// Ammount to be transferred
	Amount uint64 `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	// TODO: if this is going to stay past debug, perhaps some field indicating max fee?
	// TODO: if this is going to stay past debug, we need nonce to prevent replay attacks
	// Signature on request to confirm its validitiy
	Sig                  []byte   `protobuf:"bytes,4,opt,name=Sig,proto3" json:"Sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountTransferRequest) Reset()         { *m = AccountTransferRequest{} }
func (m *AccountTransferRequest) String() string { return proto.CompactTextString(m) }
func (*AccountTransferRequest) ProtoMessage()    {}
func (*AccountTransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb862c5130efc92, []int{1}
}

func (m *AccountTransferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountTransferRequest.Unmarshal(m, b)
}
func (m *AccountTransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountTransferRequest.Marshal(b, m, deterministic)
}
func (m *AccountTransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountTransferRequest.Merge(m, src)
}
func (m *AccountTransferRequest) XXX_Size() int {
	return xxx_messageInfo_AccountTransferRequest.Size(m)
}
func (m *AccountTransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountTransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountTransferRequest proto.InternalMessageInfo

func (m *AccountTransferRequest) GetSourcePublicKey() []byte {
	if m != nil {
		return m.SourcePublicKey
	}
	return nil
}

func (m *AccountTransferRequest) GetTargetPublicKey() []byte {
	if m != nil {
		return m.TargetPublicKey
	}
	return nil
}

func (m *AccountTransferRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *AccountTransferRequest) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type DepositCoconutCredentialRequest struct {
	// The actual credential
	Sig *scheme.ProtoSignature `protobuf:"bytes,1,opt,name=Sig,proto3" json:"Sig,omitempty"`
	// The public attributes in credential. Note that pubM[0] = H(value)
	PubM [][]byte `protobuf:"bytes,2,rep,name=PubM,proto3" json:"PubM,omitempty"`
	// Crypto materials to verify the credential + required NIZK
	Theta *scheme.ProtoThetaTumbler `protobuf:"bytes,3,opt,name=Theta,proto3" json:"Theta,omitempty"`
	// Value of the credential
	Value int32 `protobuf:"varint,4,opt,name=Value,proto3" json:"Value,omitempty"`
	// Address of the merchant to which the proof is bound
	MerchantAddress      []byte   `protobuf:"bytes,5,opt,name=MerchantAddress,proto3" json:"MerchantAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositCoconutCredentialRequest) Reset()         { *m = DepositCoconutCredentialRequest{} }
func (m *DepositCoconutCredentialRequest) String() string { return proto.CompactTextString(m) }
func (*DepositCoconutCredentialRequest) ProtoMessage()    {}
func (*DepositCoconutCredentialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb862c5130efc92, []int{2}
}

func (m *DepositCoconutCredentialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositCoconutCredentialRequest.Unmarshal(m, b)
}
func (m *DepositCoconutCredentialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositCoconutCredentialRequest.Marshal(b, m, deterministic)
}
func (m *DepositCoconutCredentialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositCoconutCredentialRequest.Merge(m, src)
}
func (m *DepositCoconutCredentialRequest) XXX_Size() int {
	return xxx_messageInfo_DepositCoconutCredentialRequest.Size(m)
}
func (m *DepositCoconutCredentialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositCoconutCredentialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DepositCoconutCredentialRequest proto.InternalMessageInfo

func (m *DepositCoconutCredentialRequest) GetSig() *scheme.ProtoSignature {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *DepositCoconutCredentialRequest) GetPubM() [][]byte {
	if m != nil {
		return m.PubM
	}
	return nil
}

func (m *DepositCoconutCredentialRequest) GetTheta() *scheme.ProtoThetaTumbler {
	if m != nil {
		return m.Theta
	}
	return nil
}

func (m *DepositCoconutCredentialRequest) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *DepositCoconutCredentialRequest) GetMerchantAddress() []byte {
	if m != nil {
		return m.MerchantAddress
	}
	return nil
}

// We have defined similar messages before for the grpc provider, however, we can't rely on their definitions
// in case something changed here (or there)
type VerifyCoconutCredentialRequest struct {
	Sig                  *scheme.ProtoSignature `protobuf:"bytes,1,opt,name=Sig,proto3" json:"Sig,omitempty"`
	PubM                 [][]byte               `protobuf:"bytes,2,rep,name=PubM,proto3" json:"PubM,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *VerifyCoconutCredentialRequest) Reset()         { *m = VerifyCoconutCredentialRequest{} }
func (m *VerifyCoconutCredentialRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyCoconutCredentialRequest) ProtoMessage()    {}
func (*VerifyCoconutCredentialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb862c5130efc92, []int{3}
}

func (m *VerifyCoconutCredentialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyCoconutCredentialRequest.Unmarshal(m, b)
}
func (m *VerifyCoconutCredentialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyCoconutCredentialRequest.Marshal(b, m, deterministic)
}
func (m *VerifyCoconutCredentialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyCoconutCredentialRequest.Merge(m, src)
}
func (m *VerifyCoconutCredentialRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyCoconutCredentialRequest.Size(m)
}
func (m *VerifyCoconutCredentialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyCoconutCredentialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyCoconutCredentialRequest proto.InternalMessageInfo

func (m *VerifyCoconutCredentialRequest) GetSig() *scheme.ProtoSignature {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *VerifyCoconutCredentialRequest) GetPubM() [][]byte {
	if m != nil {
		return m.PubM
	}
	return nil
}

func init() {
	proto.RegisterType((*NewAccountRequest)(nil), "transaction.NewAccountRequest")
	proto.RegisterType((*AccountTransferRequest)(nil), "transaction.AccountTransferRequest")
	proto.RegisterType((*DepositCoconutCredentialRequest)(nil), "transaction.DepositCoconutCredentialRequest")
	proto.RegisterType((*VerifyCoconutCredentialRequest)(nil), "transaction.VerifyCoconutCredentialRequest")
}

func init() {
	proto.RegisterFile("tendermint/nymabci/transaction/proto/types.proto", fileDescriptor_ffb862c5130efc92)
}

var fileDescriptor_ffb862c5130efc92 = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x55, 0xb6, 0xcd, 0x4a, 0xb8, 0x2b, 0x01, 0x16, 0x5a, 0xa2, 0x0a, 0x2d, 0xab, 0x5e, 0x28,
	0x97, 0xb8, 0x5a, 0xae, 0x08, 0xa9, 0x2c, 0x12, 0x07, 0xb4, 0xa8, 0x4a, 0xa3, 0x3d, 0x70, 0x41,
	0x8e, 0x33, 0x4d, 0x8d, 0x12, 0x3b, 0xd8, 0x63, 0x41, 0xf8, 0x10, 0x3e, 0x8c, 0x2f, 0x42, 0x71,
	0x52, 0xa5, 0x04, 0xa9, 0xb7, 0xbd, 0x8d, 0xdf, 0x3c, 0xfb, 0xbd, 0x37, 0x1e, 0xb2, 0x42, 0x50,
	0x39, 0x98, 0x4a, 0x2a, 0x64, 0xaa, 0xa9, 0x78, 0x26, 0x24, 0x43, 0xc3, 0x95, 0xe5, 0x02, 0xa5,
	0x56, 0xac, 0x36, 0x1a, 0x35, 0xc3, 0xa6, 0x06, 0x1b, 0xfb, 0x9a, 0xce, 0x8e, 0xda, 0xf3, 0x57,
	0xc2, 0x34, 0x35, 0x6a, 0x26, 0xb4, 0xd0, 0xca, 0x21, 0xb3, 0x62, 0x0f, 0x15, 0xfc, 0x7f, 0x6b,
	0x1e, 0x9f, 0x24, 0xba, 0x2a, 0x2b, 0xc1, 0x1c, 0xf1, 0x17, 0x82, 0x3c, 0xfd, 0x0c, 0x3f, 0xd6,
	0x42, 0x68, 0xa7, 0x30, 0x81, 0xef, 0x0e, 0x2c, 0xd2, 0x17, 0xe4, 0xd1, 0xc6, 0x65, 0xa5, 0x14,
	0x9f, 0xa0, 0x89, 0x82, 0xeb, 0x60, 0x79, 0x91, 0x0c, 0x00, 0xbd, 0x22, 0xe4, 0xd6, 0x40, 0x0e,
	0x0a, 0x25, 0x2f, 0xa3, 0x33, 0xdf, 0x3e, 0x42, 0xe8, 0x13, 0x32, 0xd9, 0xca, 0x22, 0x9a, 0xf8,
	0x46, 0x5b, 0x2e, 0x7e, 0x07, 0xe4, 0xb2, 0x97, 0x48, 0xdb, 0x50, 0x3b, 0x30, 0x07, 0xa9, 0x25,
	0x79, 0xbc, 0xd5, 0xce, 0x08, 0x18, 0x0b, 0x8e, 0xe1, 0x96, 0x99, 0x72, 0x53, 0x00, 0x0e, 0xcc,
	0x4e, 0x7b, 0x0c, 0xd3, 0x4b, 0x72, 0xbe, 0xae, 0x5a, 0x31, 0xef, 0x61, 0x9a, 0xf4, 0xa7, 0x83,
	0xb1, 0xe9, 0x60, 0xec, 0x4f, 0x40, 0x5e, 0x7e, 0x80, 0x5a, 0x5b, 0x89, 0xb7, 0xdd, 0xc0, 0x86,
	0x1c, 0x07, 0x87, 0xaf, 0xbb, 0x5b, 0xad, 0xab, 0xd9, 0xcd, 0xf3, 0xb8, 0x1f, 0x6c, 0xbc, 0x69,
	0xc7, 0xb7, 0x95, 0x85, 0xe2, 0xe8, 0x0c, 0xf8, 0xe7, 0x28, 0x25, 0xd3, 0x8d, 0xcb, 0xee, 0xa2,
	0xb3, 0xeb, 0xc9, 0xf2, 0x22, 0xf1, 0x35, 0x5d, 0x91, 0x30, 0xdd, 0x03, 0x72, 0xef, 0x65, 0x76,
	0x33, 0xff, 0xf7, 0x01, 0xdf, 0x4a, 0xbb, 0x6f, 0x49, 0x3a, 0x22, 0x7d, 0x46, 0xc2, 0x7b, 0x5e,
	0x3a, 0xf0, 0x46, 0xc3, 0xa4, 0x3b, 0xb4, 0xf1, 0xef, 0xc0, 0x88, 0x3d, 0x57, 0xb8, 0xce, 0x73,
	0x03, 0xd6, 0x46, 0x61, 0x17, 0x7f, 0x04, 0x2f, 0xbe, 0x92, 0xab, 0x7b, 0x30, 0x72, 0xd7, 0x3c,
	0x50, 0xa4, 0xf7, 0xef, 0xbe, 0xbc, 0x5d, 0xfd, 0xe4, 0x82, 0x67, 0xb1, 0x36, 0x05, 0xfb, 0x66,
	0xd1, 0x89, 0x5f, 0x8d, 0x62, 0xbd, 0xdc, 0x47, 0xcd, 0x4e, 0xef, 0x7a, 0x76, 0xee, 0x57, 0xef,
	0xcd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x34, 0xd0, 0x36, 0x2c, 0x14, 0x03, 0x00, 0x00,
}
