// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/grpc/services/proto/services.proto

package services

import (
	commands "0xacab.org/jstuczyn/CoconutGo/common/comm/commands"
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("common/grpc/services/proto/services.proto", fileDescriptor_eac07ec6ca06236d)
}

var fileDescriptor_eac07ec6ca06236d = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xe9, 0xa5, 0x94, 0x1c, 0x04, 0x23, 0x56, 0xa9, 0x0a, 0x7a, 0x11, 0xbc, 0x6c, 0x64,
	0xf5, 0x2e, 0xb6, 0x60, 0x11, 0x41, 0x44, 0x51, 0xd0, 0xdb, 0x6e, 0x76, 0x5c, 0x22, 0x6d, 0x66,
	0xcd, 0xcc, 0x16, 0xd7, 0x37, 0xf2, 0xfd, 0x7c, 0x00, 0xe9, 0x76, 0xb3, 0xc5, 0xb4, 0x7a, 0x49,
	0x98, 0xfc, 0xf3, 0x7f, 0xf9, 0x87, 0x44, 0x9c, 0x68, 0x9c, 0x4e, 0xd1, 0xaa, 0xdc, 0x15, 0x5a,
	0x11, 0xb8, 0x99, 0xd1, 0x40, 0xaa, 0x70, 0xc8, 0xd8, 0x96, 0x51, 0x5d, 0xca, 0x9e, 0xaf, 0x07,
	0xc7, 0x8d, 0x69, 0xbe, 0xd5, 0x4b, 0x62, 0x33, 0x6f, 0xe2, 0xaa, 0xf0, 0x8e, 0xf8, 0xbb, 0x23,
	0xba, 0xd7, 0x44, 0x25, 0x38, 0xf9, 0x2c, 0xe4, 0x18, 0xf8, 0x09, 0x9c, 0x79, 0x35, 0x3a, 0x61,
	0x83, 0xf6, 0x06, 0x2a, 0x79, 0x18, 0x79, 0x77, 0x14, 0x48, 0xf7, 0xf0, 0x5e, 0x02, 0xf1, 0xe0,
	0xe8, 0x9f, 0x0e, 0x2a, 0xd0, 0x12, 0xc8, 0x0b, 0xb1, 0xf1, 0x60, 0x72, 0x7b, 0xc9, 0xec, 0x4c,
	0x5a, 0x32, 0x90, 0xdc, 0x5e, 0x9a, 0xe6, 0x8a, 0x67, 0xf5, 0xc3, 0xe3, 0x06, 0x70, 0x2b, 0xb6,
	0x86, 0x13, 0x63, 0xb3, 0x80, 0x32, 0x58, 0xb6, 0xb7, 0xb2, 0x47, 0xed, 0xad, 0xd5, 0x16, 0xbc,
	0xf8, 0xab, 0x23, 0x7a, 0x77, 0x0e, 0x67, 0x26, 0x03, 0x27, 0xaf, 0xc4, 0x66, 0x1d, 0xbc, 0x1a,
	0x39, 0xc8, 0xc0, 0xb2, 0x49, 0x26, 0x24, 0x77, 0x82, 0xa9, 0xda, 0x71, 0x77, 0x57, 0x85, 0x26,
	0xe4, 0xa3, 0xe8, 0xd7, 0x37, 0xad, 0xc2, 0xf6, 0x83, 0x2c, 0xbf, 0x89, 0x07, 0x7f, 0xa8, 0x0b,
	0xec, 0xf0, 0xfc, 0x25, 0x3e, 0xfd, 0x48, 0x74, 0x92, 0x46, 0xe8, 0x72, 0xf5, 0x46, 0x5c, 0xea,
	0xcf, 0xca, 0xaa, 0x11, 0x6a, 0xb4, 0x25, 0x8f, 0x51, 0xad, 0xfb, 0x1f, 0x69, 0xb7, 0x7e, 0xdf,
	0xb3, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8f, 0xcf, 0x13, 0x0a, 0x3e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IssuerClient is the client API for Issuer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IssuerClient interface {
	GetVerificationKey(ctx context.Context, in *commands.VerificationKeyRequest, opts ...grpc.CallOption) (*commands.VerificationKeyResponse, error)
	SignAttributes(ctx context.Context, in *commands.SignRequest, opts ...grpc.CallOption) (*commands.SignResponse, error)
	BlindSignAttributes(ctx context.Context, in *commands.BlindSignRequest, opts ...grpc.CallOption) (*commands.BlindSignResponse, error)
}

type issuerClient struct {
	cc *grpc.ClientConn
}

func NewIssuerClient(cc *grpc.ClientConn) IssuerClient {
	return &issuerClient{cc}
}

func (c *issuerClient) GetVerificationKey(ctx context.Context, in *commands.VerificationKeyRequest, opts ...grpc.CallOption) (*commands.VerificationKeyResponse, error) {
	out := new(commands.VerificationKeyResponse)
	err := c.cc.Invoke(ctx, "/services.Issuer/GetVerificationKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issuerClient) SignAttributes(ctx context.Context, in *commands.SignRequest, opts ...grpc.CallOption) (*commands.SignResponse, error) {
	out := new(commands.SignResponse)
	err := c.cc.Invoke(ctx, "/services.Issuer/SignAttributes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issuerClient) BlindSignAttributes(ctx context.Context, in *commands.BlindSignRequest, opts ...grpc.CallOption) (*commands.BlindSignResponse, error) {
	out := new(commands.BlindSignResponse)
	err := c.cc.Invoke(ctx, "/services.Issuer/BlindSignAttributes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IssuerServer is the server API for Issuer service.
type IssuerServer interface {
	GetVerificationKey(context.Context, *commands.VerificationKeyRequest) (*commands.VerificationKeyResponse, error)
	SignAttributes(context.Context, *commands.SignRequest) (*commands.SignResponse, error)
	BlindSignAttributes(context.Context, *commands.BlindSignRequest) (*commands.BlindSignResponse, error)
}

// UnimplementedIssuerServer can be embedded to have forward compatible implementations.
type UnimplementedIssuerServer struct {
}

func (*UnimplementedIssuerServer) GetVerificationKey(ctx context.Context, req *commands.VerificationKeyRequest) (*commands.VerificationKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVerificationKey not implemented")
}
func (*UnimplementedIssuerServer) SignAttributes(ctx context.Context, req *commands.SignRequest) (*commands.SignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignAttributes not implemented")
}
func (*UnimplementedIssuerServer) BlindSignAttributes(ctx context.Context, req *commands.BlindSignRequest) (*commands.BlindSignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlindSignAttributes not implemented")
}

func RegisterIssuerServer(s *grpc.Server, srv IssuerServer) {
	s.RegisterService(&_Issuer_serviceDesc, srv)
}

func _Issuer_GetVerificationKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commands.VerificationKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServer).GetVerificationKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.Issuer/GetVerificationKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServer).GetVerificationKey(ctx, req.(*commands.VerificationKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Issuer_SignAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commands.SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServer).SignAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.Issuer/SignAttributes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServer).SignAttributes(ctx, req.(*commands.SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Issuer_BlindSignAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commands.BlindSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServer).BlindSignAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.Issuer/BlindSignAttributes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServer).BlindSignAttributes(ctx, req.(*commands.BlindSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Issuer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.Issuer",
	HandlerType: (*IssuerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVerificationKey",
			Handler:    _Issuer_GetVerificationKey_Handler,
		},
		{
			MethodName: "SignAttributes",
			Handler:    _Issuer_SignAttributes_Handler,
		},
		{
			MethodName: "BlindSignAttributes",
			Handler:    _Issuer_BlindSignAttributes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/grpc/services/proto/services.proto",
}

// ProviderClient is the client API for Provider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProviderClient interface {
	VerifyCredentials(ctx context.Context, in *commands.VerifyRequest, opts ...grpc.CallOption) (*commands.VerifyResponse, error)
	BlindVerifyCredentials(ctx context.Context, in *commands.BlindVerifyRequest, opts ...grpc.CallOption) (*commands.BlindVerifyResponse, error)
}

type providerClient struct {
	cc *grpc.ClientConn
}

func NewProviderClient(cc *grpc.ClientConn) ProviderClient {
	return &providerClient{cc}
}

func (c *providerClient) VerifyCredentials(ctx context.Context, in *commands.VerifyRequest, opts ...grpc.CallOption) (*commands.VerifyResponse, error) {
	out := new(commands.VerifyResponse)
	err := c.cc.Invoke(ctx, "/services.Provider/VerifyCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) BlindVerifyCredentials(ctx context.Context, in *commands.BlindVerifyRequest, opts ...grpc.CallOption) (*commands.BlindVerifyResponse, error) {
	out := new(commands.BlindVerifyResponse)
	err := c.cc.Invoke(ctx, "/services.Provider/BlindVerifyCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderServer is the server API for Provider service.
type ProviderServer interface {
	VerifyCredentials(context.Context, *commands.VerifyRequest) (*commands.VerifyResponse, error)
	BlindVerifyCredentials(context.Context, *commands.BlindVerifyRequest) (*commands.BlindVerifyResponse, error)
}

// UnimplementedProviderServer can be embedded to have forward compatible implementations.
type UnimplementedProviderServer struct {
}

func (*UnimplementedProviderServer) VerifyCredentials(ctx context.Context, req *commands.VerifyRequest) (*commands.VerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyCredentials not implemented")
}
func (*UnimplementedProviderServer) BlindVerifyCredentials(ctx context.Context, req *commands.BlindVerifyRequest) (*commands.BlindVerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlindVerifyCredentials not implemented")
}

func RegisterProviderServer(s *grpc.Server, srv ProviderServer) {
	s.RegisterService(&_Provider_serviceDesc, srv)
}

func _Provider_VerifyCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commands.VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).VerifyCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.Provider/VerifyCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).VerifyCredentials(ctx, req.(*commands.VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_BlindVerifyCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commands.BlindVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).BlindVerifyCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.Provider/BlindVerifyCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).BlindVerifyCredentials(ctx, req.(*commands.BlindVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Provider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.Provider",
	HandlerType: (*ProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyCredentials",
			Handler:    _Provider_VerifyCredentials_Handler,
		},
		{
			MethodName: "BlindVerifyCredentials",
			Handler:    _Provider_BlindVerifyCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/grpc/services/proto/services.proto",
}
