// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crypto/elgamal/proto/types.proto

package elgamal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtoEncryption struct {
	C1                   []byte   `protobuf:"bytes,1,opt,name=C1,proto3" json:"C1,omitempty"`
	C2                   []byte   `protobuf:"bytes,2,opt,name=C2,proto3" json:"C2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoEncryption) Reset()         { *m = ProtoEncryption{} }
func (m *ProtoEncryption) String() string { return proto.CompactTextString(m) }
func (*ProtoEncryption) ProtoMessage()    {}
func (*ProtoEncryption) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4e4601cca9348f7, []int{0}
}

func (m *ProtoEncryption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoEncryption.Unmarshal(m, b)
}
func (m *ProtoEncryption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoEncryption.Marshal(b, m, deterministic)
}
func (m *ProtoEncryption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoEncryption.Merge(m, src)
}
func (m *ProtoEncryption) XXX_Size() int {
	return xxx_messageInfo_ProtoEncryption.Size(m)
}
func (m *ProtoEncryption) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoEncryption.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoEncryption proto.InternalMessageInfo

func (m *ProtoEncryption) GetC1() []byte {
	if m != nil {
		return m.C1
	}
	return nil
}

func (m *ProtoEncryption) GetC2() []byte {
	if m != nil {
		return m.C2
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtoEncryption)(nil), "elgamal.ProtoEncryption")
}

func init() { proto.RegisterFile("crypto/elgamal/proto/types.proto", fileDescriptor_a4e4601cca9348f7) }

var fileDescriptor_a4e4601cca9348f7 = []byte{
	// 137 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x48, 0x2e, 0xaa, 0x2c,
	0x28, 0xc9, 0xd7, 0x4f, 0xcd, 0x49, 0x4f, 0xcc, 0x4d, 0xcc, 0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9,
	0xd7, 0x2f, 0xa9, 0x2c, 0x48, 0x2d, 0xd6, 0x03, 0xb3, 0x85, 0xd8, 0xa1, 0x52, 0x4a, 0x86, 0x5c,
	0xfc, 0x01, 0x20, 0x11, 0xd7, 0x3c, 0xb0, 0x9e, 0xcc, 0xfc, 0x3c, 0x21, 0x3e, 0x2e, 0x26, 0x67,
	0x43, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x26, 0x67, 0x43, 0x30, 0xdf, 0x48, 0x82, 0x09,
	0xca, 0x37, 0x72, 0xd2, 0x8b, 0xd2, 0x49, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf,
	0xd5, 0xcf, 0x2a, 0x2e, 0x29, 0x4d, 0xae, 0xaa, 0xcc, 0xd3, 0x77, 0xce, 0x4f, 0xce, 0xcf, 0x2b,
	0x2d, 0x71, 0xcf, 0xd7, 0x47, 0xb5, 0x3d, 0x89, 0x0d, 0x6c, 0xa5, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0xd0, 0x56, 0x47, 0x80, 0x96, 0x00, 0x00, 0x00,
}
