// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/comm/commands/proto/types.proto

package commands

import (
	scheme "0xacab.org/jstuczyn/CoconutGo/crypto/coconut/scheme"
	elgamal "0xacab.org/jstuczyn/CoconutGo/crypto/elgamal"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_OK                  StatusCode = 0
	StatusCode_UNKNOWN             StatusCode = 1
	StatusCode_INVALID_COMMAND     StatusCode = 2
	StatusCode_INVALID_ARGUMENTS   StatusCode = 3
	StatusCode_PROCESSING_ERROR    StatusCode = 4
	StatusCode_NOT_IMPLEMENTED     StatusCode = 5
	StatusCode_REQUEST_TIMEOUT     StatusCode = 6
	StatusCode_UNAVAILABLE         StatusCode = 7
	StatusCode_INVALID_TRANSACTION StatusCode = 8
	StatusCode_INVALID_BINDING     StatusCode = 9
	StatusCode_INVALID_SIGNATURE   StatusCode = 10
	StatusCode_TX_NOT_ON_CHAIN     StatusCode = 11
	StatusCode_NOT_PROCESSED_YET   StatusCode = 12
)

var StatusCode_name = map[int32]string{
	0:  "OK",
	1:  "UNKNOWN",
	2:  "INVALID_COMMAND",
	3:  "INVALID_ARGUMENTS",
	4:  "PROCESSING_ERROR",
	5:  "NOT_IMPLEMENTED",
	6:  "REQUEST_TIMEOUT",
	7:  "UNAVAILABLE",
	8:  "INVALID_TRANSACTION",
	9:  "INVALID_BINDING",
	10: "INVALID_SIGNATURE",
	11: "TX_NOT_ON_CHAIN",
	12: "NOT_PROCESSED_YET",
}

var StatusCode_value = map[string]int32{
	"OK":                  0,
	"UNKNOWN":             1,
	"INVALID_COMMAND":     2,
	"INVALID_ARGUMENTS":   3,
	"PROCESSING_ERROR":    4,
	"NOT_IMPLEMENTED":     5,
	"REQUEST_TIMEOUT":     6,
	"UNAVAILABLE":         7,
	"INVALID_TRANSACTION": 8,
	"INVALID_BINDING":     9,
	"INVALID_SIGNATURE":   10,
	"TX_NOT_ON_CHAIN":     11,
	"NOT_PROCESSED_YET":   12,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{0}
}

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SignRequest struct {
	PubM                 [][]byte `protobuf:"bytes,1,rep,name=pubM,proto3" json:"pubM,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignRequest) Reset()         { *m = SignRequest{} }
func (m *SignRequest) String() string { return proto.CompactTextString(m) }
func (*SignRequest) ProtoMessage()    {}
func (*SignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{1}
}

func (m *SignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignRequest.Unmarshal(m, b)
}
func (m *SignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignRequest.Marshal(b, m, deterministic)
}
func (m *SignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignRequest.Merge(m, src)
}
func (m *SignRequest) XXX_Size() int {
	return xxx_messageInfo_SignRequest.Size(m)
}
func (m *SignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignRequest proto.InternalMessageInfo

func (m *SignRequest) GetPubM() [][]byte {
	if m != nil {
		return m.PubM
	}
	return nil
}

type SignResponse struct {
	Sig                  *scheme.ProtoSignature `protobuf:"bytes,1,opt,name=sig,proto3" json:"sig,omitempty"`
	IssuerID             int64                  `protobuf:"varint,2,opt,name=IssuerID,json=issuerID,proto3" json:"IssuerID,omitempty"`
	Status               *Status                `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SignResponse) Reset()         { *m = SignResponse{} }
func (m *SignResponse) String() string { return proto.CompactTextString(m) }
func (*SignResponse) ProtoMessage()    {}
func (*SignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{2}
}

func (m *SignResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignResponse.Unmarshal(m, b)
}
func (m *SignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignResponse.Marshal(b, m, deterministic)
}
func (m *SignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignResponse.Merge(m, src)
}
func (m *SignResponse) XXX_Size() int {
	return xxx_messageInfo_SignResponse.Size(m)
}
func (m *SignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignResponse proto.InternalMessageInfo

func (m *SignResponse) GetSig() *scheme.ProtoSignature {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *SignResponse) GetIssuerID() int64 {
	if m != nil {
		return m.IssuerID
	}
	return 0
}

func (m *SignResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type VerificationKeyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerificationKeyRequest) Reset()         { *m = VerificationKeyRequest{} }
func (m *VerificationKeyRequest) String() string { return proto.CompactTextString(m) }
func (*VerificationKeyRequest) ProtoMessage()    {}
func (*VerificationKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{3}
}

func (m *VerificationKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerificationKeyRequest.Unmarshal(m, b)
}
func (m *VerificationKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerificationKeyRequest.Marshal(b, m, deterministic)
}
func (m *VerificationKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationKeyRequest.Merge(m, src)
}
func (m *VerificationKeyRequest) XXX_Size() int {
	return xxx_messageInfo_VerificationKeyRequest.Size(m)
}
func (m *VerificationKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationKeyRequest proto.InternalMessageInfo

type VerificationKeyResponse struct {
	Vk                   *scheme.ProtoVerificationKey `protobuf:"bytes,1,opt,name=vk,proto3" json:"vk,omitempty"`
	IssuerID             int64                        `protobuf:"varint,2,opt,name=IssuerID,json=issuerID,proto3" json:"IssuerID,omitempty"`
	Status               *Status                      `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *VerificationKeyResponse) Reset()         { *m = VerificationKeyResponse{} }
func (m *VerificationKeyResponse) String() string { return proto.CompactTextString(m) }
func (*VerificationKeyResponse) ProtoMessage()    {}
func (*VerificationKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{4}
}

func (m *VerificationKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerificationKeyResponse.Unmarshal(m, b)
}
func (m *VerificationKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerificationKeyResponse.Marshal(b, m, deterministic)
}
func (m *VerificationKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationKeyResponse.Merge(m, src)
}
func (m *VerificationKeyResponse) XXX_Size() int {
	return xxx_messageInfo_VerificationKeyResponse.Size(m)
}
func (m *VerificationKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationKeyResponse proto.InternalMessageInfo

func (m *VerificationKeyResponse) GetVk() *scheme.ProtoVerificationKey {
	if m != nil {
		return m.Vk
	}
	return nil
}

func (m *VerificationKeyResponse) GetIssuerID() int64 {
	if m != nil {
		return m.IssuerID
	}
	return 0
}

func (m *VerificationKeyResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type VerifyRequest struct {
	Sig                  *scheme.ProtoSignature `protobuf:"bytes,1,opt,name=sig,proto3" json:"sig,omitempty"`
	PubM                 [][]byte               `protobuf:"bytes,2,rep,name=pubM,proto3" json:"pubM,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *VerifyRequest) Reset()         { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()    {}
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{5}
}

func (m *VerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRequest.Unmarshal(m, b)
}
func (m *VerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRequest.Marshal(b, m, deterministic)
}
func (m *VerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRequest.Merge(m, src)
}
func (m *VerifyRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyRequest.Size(m)
}
func (m *VerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRequest proto.InternalMessageInfo

func (m *VerifyRequest) GetSig() *scheme.ProtoSignature {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *VerifyRequest) GetPubM() [][]byte {
	if m != nil {
		return m.PubM
	}
	return nil
}

type VerifyResponse struct {
	IsValid              bool     `protobuf:"varint,1,opt,name=isValid,proto3" json:"isValid,omitempty"`
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyResponse) Reset()         { *m = VerifyResponse{} }
func (m *VerifyResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyResponse) ProtoMessage()    {}
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{6}
}

func (m *VerifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyResponse.Unmarshal(m, b)
}
func (m *VerifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyResponse.Marshal(b, m, deterministic)
}
func (m *VerifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyResponse.Merge(m, src)
}
func (m *VerifyResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyResponse.Size(m)
}
func (m *VerifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyResponse proto.InternalMessageInfo

func (m *VerifyResponse) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

func (m *VerifyResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type BlindSignRequest struct {
	PubM                 [][]byte                `protobuf:"bytes,1,rep,name=pubM,proto3" json:"pubM,omitempty"`
	Lambda               *scheme.ProtoLambda     `protobuf:"bytes,2,opt,name=lambda,proto3" json:"lambda,omitempty"`
	EgPub                *elgamal.ProtoPublicKey `protobuf:"bytes,3,opt,name=egPub,proto3" json:"egPub,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *BlindSignRequest) Reset()         { *m = BlindSignRequest{} }
func (m *BlindSignRequest) String() string { return proto.CompactTextString(m) }
func (*BlindSignRequest) ProtoMessage()    {}
func (*BlindSignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{7}
}

func (m *BlindSignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlindSignRequest.Unmarshal(m, b)
}
func (m *BlindSignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlindSignRequest.Marshal(b, m, deterministic)
}
func (m *BlindSignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlindSignRequest.Merge(m, src)
}
func (m *BlindSignRequest) XXX_Size() int {
	return xxx_messageInfo_BlindSignRequest.Size(m)
}
func (m *BlindSignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlindSignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlindSignRequest proto.InternalMessageInfo

func (m *BlindSignRequest) GetPubM() [][]byte {
	if m != nil {
		return m.PubM
	}
	return nil
}

func (m *BlindSignRequest) GetLambda() *scheme.ProtoLambda {
	if m != nil {
		return m.Lambda
	}
	return nil
}

func (m *BlindSignRequest) GetEgPub() *elgamal.ProtoPublicKey {
	if m != nil {
		return m.EgPub
	}
	return nil
}

type BlindSignResponse struct {
	Sig                  *scheme.ProtoBlindedSignature `protobuf:"bytes,1,opt,name=sig,proto3" json:"sig,omitempty"`
	IssuerID             int64                         `protobuf:"varint,2,opt,name=IssuerID,json=issuerID,proto3" json:"IssuerID,omitempty"`
	Status               *Status                       `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *BlindSignResponse) Reset()         { *m = BlindSignResponse{} }
func (m *BlindSignResponse) String() string { return proto.CompactTextString(m) }
func (*BlindSignResponse) ProtoMessage()    {}
func (*BlindSignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{8}
}

func (m *BlindSignResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlindSignResponse.Unmarshal(m, b)
}
func (m *BlindSignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlindSignResponse.Marshal(b, m, deterministic)
}
func (m *BlindSignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlindSignResponse.Merge(m, src)
}
func (m *BlindSignResponse) XXX_Size() int {
	return xxx_messageInfo_BlindSignResponse.Size(m)
}
func (m *BlindSignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlindSignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlindSignResponse proto.InternalMessageInfo

func (m *BlindSignResponse) GetSig() *scheme.ProtoBlindedSignature {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *BlindSignResponse) GetIssuerID() int64 {
	if m != nil {
		return m.IssuerID
	}
	return 0
}

func (m *BlindSignResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type BlindVerifyRequest struct {
	Sig                  *scheme.ProtoSignature `protobuf:"bytes,1,opt,name=sig,proto3" json:"sig,omitempty"`
	PubM                 [][]byte               `protobuf:"bytes,2,rep,name=pubM,proto3" json:"pubM,omitempty"`
	Theta                *scheme.ProtoTheta     `protobuf:"bytes,3,opt,name=theta,proto3" json:"theta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BlindVerifyRequest) Reset()         { *m = BlindVerifyRequest{} }
func (m *BlindVerifyRequest) String() string { return proto.CompactTextString(m) }
func (*BlindVerifyRequest) ProtoMessage()    {}
func (*BlindVerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{9}
}

func (m *BlindVerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlindVerifyRequest.Unmarshal(m, b)
}
func (m *BlindVerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlindVerifyRequest.Marshal(b, m, deterministic)
}
func (m *BlindVerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlindVerifyRequest.Merge(m, src)
}
func (m *BlindVerifyRequest) XXX_Size() int {
	return xxx_messageInfo_BlindVerifyRequest.Size(m)
}
func (m *BlindVerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlindVerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlindVerifyRequest proto.InternalMessageInfo

func (m *BlindVerifyRequest) GetSig() *scheme.ProtoSignature {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *BlindVerifyRequest) GetPubM() [][]byte {
	if m != nil {
		return m.PubM
	}
	return nil
}

func (m *BlindVerifyRequest) GetTheta() *scheme.ProtoTheta {
	if m != nil {
		return m.Theta
	}
	return nil
}

type BlindVerifyResponse struct {
	IsValid              bool     `protobuf:"varint,1,opt,name=isValid,proto3" json:"isValid,omitempty"`
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlindVerifyResponse) Reset()         { *m = BlindVerifyResponse{} }
func (m *BlindVerifyResponse) String() string { return proto.CompactTextString(m) }
func (*BlindVerifyResponse) ProtoMessage()    {}
func (*BlindVerifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{10}
}

func (m *BlindVerifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlindVerifyResponse.Unmarshal(m, b)
}
func (m *BlindVerifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlindVerifyResponse.Marshal(b, m, deterministic)
}
func (m *BlindVerifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlindVerifyResponse.Merge(m, src)
}
func (m *BlindVerifyResponse) XXX_Size() int {
	return xxx_messageInfo_BlindVerifyResponse.Size(m)
}
func (m *BlindVerifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlindVerifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlindVerifyResponse proto.InternalMessageInfo

func (m *BlindVerifyResponse) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

func (m *BlindVerifyResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetCredentialRequest struct {
	// Public Key of the user used to derive account address and validate signature.
	PublicKey []byte `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	// ElGamal Public Key used to encrypt public attributes by the IA and verify the NIZKs.
	EgPub *elgamal.ProtoPublicKey `protobuf:"bytes,2,opt,name=egPub,proto3" json:"egPub,omitempty"`
	// Cryptographic material needed for the blind sign - commitment to values, encryptions and NIZKs.
	Lambda *scheme.ProtoLambda `protobuf:"bytes,3,opt,name=lambda,proto3" json:"lambda,omitempty"`
	// Value of the desired credential.
	Value int64 `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	// The public attributes to be embedded in the credential. Note that pubM[0] = BIG(value).
	PubM [][]byte `protobuf:"bytes,5,rep,name=pubM,proto3" json:"pubM,omitempty"`
	// Nonce sent to the chain to request the transfer of tokens to the hlding account.
	Nonce []byte `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Hash of Tx that includes transfer of the tokens to the pipe account.
	TxHash []byte `protobuf:"bytes,7,opt,name=txHash,proto3" json:"txHash,omitempty"`
	// Signature on {PublicKey, Value, Nonce, txHash} to confirm validitiy of the request.
	Sig                  []byte   `protobuf:"bytes,8,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCredentialRequest) Reset()         { *m = GetCredentialRequest{} }
func (m *GetCredentialRequest) String() string { return proto.CompactTextString(m) }
func (*GetCredentialRequest) ProtoMessage()    {}
func (*GetCredentialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{11}
}

func (m *GetCredentialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCredentialRequest.Unmarshal(m, b)
}
func (m *GetCredentialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCredentialRequest.Marshal(b, m, deterministic)
}
func (m *GetCredentialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCredentialRequest.Merge(m, src)
}
func (m *GetCredentialRequest) XXX_Size() int {
	return xxx_messageInfo_GetCredentialRequest.Size(m)
}
func (m *GetCredentialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCredentialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCredentialRequest proto.InternalMessageInfo

func (m *GetCredentialRequest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *GetCredentialRequest) GetEgPub() *elgamal.ProtoPublicKey {
	if m != nil {
		return m.EgPub
	}
	return nil
}

func (m *GetCredentialRequest) GetLambda() *scheme.ProtoLambda {
	if m != nil {
		return m.Lambda
	}
	return nil
}

func (m *GetCredentialRequest) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *GetCredentialRequest) GetPubM() [][]byte {
	if m != nil {
		return m.PubM
	}
	return nil
}

func (m *GetCredentialRequest) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *GetCredentialRequest) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *GetCredentialRequest) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type GetCredentialResponse struct {
	Sig                  *scheme.ProtoBlindedSignature `protobuf:"bytes,1,opt,name=sig,proto3" json:"sig,omitempty"`
	Status               *Status                       `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *GetCredentialResponse) Reset()         { *m = GetCredentialResponse{} }
func (m *GetCredentialResponse) String() string { return proto.CompactTextString(m) }
func (*GetCredentialResponse) ProtoMessage()    {}
func (*GetCredentialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{12}
}

func (m *GetCredentialResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCredentialResponse.Unmarshal(m, b)
}
func (m *GetCredentialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCredentialResponse.Marshal(b, m, deterministic)
}
func (m *GetCredentialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCredentialResponse.Merge(m, src)
}
func (m *GetCredentialResponse) XXX_Size() int {
	return xxx_messageInfo_GetCredentialResponse.Size(m)
}
func (m *GetCredentialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCredentialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCredentialResponse proto.InternalMessageInfo

func (m *GetCredentialResponse) GetSig() *scheme.ProtoBlindedSignature {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *GetCredentialResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

// Sent by user to some service provider
type SpendCredentialRequest struct {
	// The actual credential
	Sig *scheme.ProtoSignature `protobuf:"bytes,1,opt,name=Sig,json=sig,proto3" json:"Sig,omitempty"`
	// The public attributes in credential. Note that pubM[0] = BIG(value)
	PubM [][]byte `protobuf:"bytes,2,rep,name=PubM,json=pubM,proto3" json:"PubM,omitempty"`
	// Crypto materials to verify the credential + required NIZK; also contains g^s
	Theta *scheme.ProtoThetaTumbler `protobuf:"bytes,3,opt,name=Theta,json=theta,proto3" json:"Theta,omitempty"`
	// Value of the credential
	Value int64 `protobuf:"varint,4,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	// Address of the merchant to which the proof is bound. Included so that the provider could verify it
	MerchantAddress      []byte   `protobuf:"bytes,5,opt,name=MerchantAddress,json=merchantAddress,proto3" json:"MerchantAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpendCredentialRequest) Reset()         { *m = SpendCredentialRequest{} }
func (m *SpendCredentialRequest) String() string { return proto.CompactTextString(m) }
func (*SpendCredentialRequest) ProtoMessage()    {}
func (*SpendCredentialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{13}
}

func (m *SpendCredentialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpendCredentialRequest.Unmarshal(m, b)
}
func (m *SpendCredentialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpendCredentialRequest.Marshal(b, m, deterministic)
}
func (m *SpendCredentialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpendCredentialRequest.Merge(m, src)
}
func (m *SpendCredentialRequest) XXX_Size() int {
	return xxx_messageInfo_SpendCredentialRequest.Size(m)
}
func (m *SpendCredentialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SpendCredentialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SpendCredentialRequest proto.InternalMessageInfo

func (m *SpendCredentialRequest) GetSig() *scheme.ProtoSignature {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *SpendCredentialRequest) GetPubM() [][]byte {
	if m != nil {
		return m.PubM
	}
	return nil
}

func (m *SpendCredentialRequest) GetTheta() *scheme.ProtoThetaTumbler {
	if m != nil {
		return m.Theta
	}
	return nil
}

func (m *SpendCredentialRequest) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *SpendCredentialRequest) GetMerchantAddress() []byte {
	if m != nil {
		return m.MerchantAddress
	}
	return nil
}

type SpendCredentialResponse struct {
	WasSuccessful        bool     `protobuf:"varint,1,opt,name=wasSuccessful,proto3" json:"wasSuccessful,omitempty"`
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpendCredentialResponse) Reset()         { *m = SpendCredentialResponse{} }
func (m *SpendCredentialResponse) String() string { return proto.CompactTextString(m) }
func (*SpendCredentialResponse) ProtoMessage()    {}
func (*SpendCredentialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{14}
}

func (m *SpendCredentialResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpendCredentialResponse.Unmarshal(m, b)
}
func (m *SpendCredentialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpendCredentialResponse.Marshal(b, m, deterministic)
}
func (m *SpendCredentialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpendCredentialResponse.Merge(m, src)
}
func (m *SpendCredentialResponse) XXX_Size() int {
	return xxx_messageInfo_SpendCredentialResponse.Size(m)
}
func (m *SpendCredentialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SpendCredentialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SpendCredentialResponse proto.InternalMessageInfo

func (m *SpendCredentialResponse) GetWasSuccessful() bool {
	if m != nil {
		return m.WasSuccessful
	}
	return false
}

func (m *SpendCredentialResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

// defines blinded credential and gamma to which it was issued
// unless client reused gamma which they shouldn't have, it will be identical to what they sent before,
// otherwise it will have additional suffix to indicate a duplicate (in given block)
type CredentialPair struct {
	Gamma []byte `protobuf:"bytes,1,opt,name=gamma,proto3" json:"gamma,omitempty"`
	// credential is defined as bytes rather than protoBlindedSignature as it in fact is marshalled proto blinded signature
	// there is no point in extra unmarshaling and further marshaling just for the sake of it.
	Credential           []byte   `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CredentialPair) Reset()         { *m = CredentialPair{} }
func (m *CredentialPair) String() string { return proto.CompactTextString(m) }
func (*CredentialPair) ProtoMessage()    {}
func (*CredentialPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{15}
}

func (m *CredentialPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CredentialPair.Unmarshal(m, b)
}
func (m *CredentialPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CredentialPair.Marshal(b, m, deterministic)
}
func (m *CredentialPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialPair.Merge(m, src)
}
func (m *CredentialPair) XXX_Size() int {
	return xxx_messageInfo_CredentialPair.Size(m)
}
func (m *CredentialPair) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialPair.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialPair proto.InternalMessageInfo

func (m *CredentialPair) GetGamma() []byte {
	if m != nil {
		return m.Gamma
	}
	return nil
}

func (m *CredentialPair) GetCredential() []byte {
	if m != nil {
		return m.Credential
	}
	return nil
}

type LookUpCredentialRequest struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Gamma                []byte   `protobuf:"bytes,2,opt,name=gamma,proto3" json:"gamma,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookUpCredentialRequest) Reset()         { *m = LookUpCredentialRequest{} }
func (m *LookUpCredentialRequest) String() string { return proto.CompactTextString(m) }
func (*LookUpCredentialRequest) ProtoMessage()    {}
func (*LookUpCredentialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{16}
}

func (m *LookUpCredentialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookUpCredentialRequest.Unmarshal(m, b)
}
func (m *LookUpCredentialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookUpCredentialRequest.Marshal(b, m, deterministic)
}
func (m *LookUpCredentialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookUpCredentialRequest.Merge(m, src)
}
func (m *LookUpCredentialRequest) XXX_Size() int {
	return xxx_messageInfo_LookUpCredentialRequest.Size(m)
}
func (m *LookUpCredentialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookUpCredentialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookUpCredentialRequest proto.InternalMessageInfo

func (m *LookUpCredentialRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *LookUpCredentialRequest) GetGamma() []byte {
	if m != nil {
		return m.Gamma
	}
	return nil
}

type LookUpCredentialResponse struct {
	CredentialPair       *CredentialPair `protobuf:"bytes,1,opt,name=credentialPair,proto3" json:"credentialPair,omitempty"`
	Status               *Status         `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LookUpCredentialResponse) Reset()         { *m = LookUpCredentialResponse{} }
func (m *LookUpCredentialResponse) String() string { return proto.CompactTextString(m) }
func (*LookUpCredentialResponse) ProtoMessage()    {}
func (*LookUpCredentialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{17}
}

func (m *LookUpCredentialResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookUpCredentialResponse.Unmarshal(m, b)
}
func (m *LookUpCredentialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookUpCredentialResponse.Marshal(b, m, deterministic)
}
func (m *LookUpCredentialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookUpCredentialResponse.Merge(m, src)
}
func (m *LookUpCredentialResponse) XXX_Size() int {
	return xxx_messageInfo_LookUpCredentialResponse.Size(m)
}
func (m *LookUpCredentialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LookUpCredentialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LookUpCredentialResponse proto.InternalMessageInfo

func (m *LookUpCredentialResponse) GetCredentialPair() *CredentialPair {
	if m != nil {
		return m.CredentialPair
	}
	return nil
}

func (m *LookUpCredentialResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type LookUpBlockCredentialsRequest struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookUpBlockCredentialsRequest) Reset()         { *m = LookUpBlockCredentialsRequest{} }
func (m *LookUpBlockCredentialsRequest) String() string { return proto.CompactTextString(m) }
func (*LookUpBlockCredentialsRequest) ProtoMessage()    {}
func (*LookUpBlockCredentialsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{18}
}

func (m *LookUpBlockCredentialsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookUpBlockCredentialsRequest.Unmarshal(m, b)
}
func (m *LookUpBlockCredentialsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookUpBlockCredentialsRequest.Marshal(b, m, deterministic)
}
func (m *LookUpBlockCredentialsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookUpBlockCredentialsRequest.Merge(m, src)
}
func (m *LookUpBlockCredentialsRequest) XXX_Size() int {
	return xxx_messageInfo_LookUpBlockCredentialsRequest.Size(m)
}
func (m *LookUpBlockCredentialsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookUpBlockCredentialsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookUpBlockCredentialsRequest proto.InternalMessageInfo

func (m *LookUpBlockCredentialsRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type LookUpBlockCredentialsResponse struct {
	Credentials          []*CredentialPair `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	Status               *Status           `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LookUpBlockCredentialsResponse) Reset()         { *m = LookUpBlockCredentialsResponse{} }
func (m *LookUpBlockCredentialsResponse) String() string { return proto.CompactTextString(m) }
func (*LookUpBlockCredentialsResponse) ProtoMessage()    {}
func (*LookUpBlockCredentialsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{19}
}

func (m *LookUpBlockCredentialsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookUpBlockCredentialsResponse.Unmarshal(m, b)
}
func (m *LookUpBlockCredentialsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookUpBlockCredentialsResponse.Marshal(b, m, deterministic)
}
func (m *LookUpBlockCredentialsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookUpBlockCredentialsResponse.Merge(m, src)
}
func (m *LookUpBlockCredentialsResponse) XXX_Size() int {
	return xxx_messageInfo_LookUpBlockCredentialsResponse.Size(m)
}
func (m *LookUpBlockCredentialsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LookUpBlockCredentialsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LookUpBlockCredentialsResponse proto.InternalMessageInfo

func (m *LookUpBlockCredentialsResponse) GetCredentials() []*CredentialPair {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *LookUpBlockCredentialsResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterEnum("commands.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterType((*Status)(nil), "commands.Status")
	proto.RegisterType((*SignRequest)(nil), "commands.SignRequest")
	proto.RegisterType((*SignResponse)(nil), "commands.SignResponse")
	proto.RegisterType((*VerificationKeyRequest)(nil), "commands.VerificationKeyRequest")
	proto.RegisterType((*VerificationKeyResponse)(nil), "commands.VerificationKeyResponse")
	proto.RegisterType((*VerifyRequest)(nil), "commands.VerifyRequest")
	proto.RegisterType((*VerifyResponse)(nil), "commands.VerifyResponse")
	proto.RegisterType((*BlindSignRequest)(nil), "commands.BlindSignRequest")
	proto.RegisterType((*BlindSignResponse)(nil), "commands.BlindSignResponse")
	proto.RegisterType((*BlindVerifyRequest)(nil), "commands.BlindVerifyRequest")
	proto.RegisterType((*BlindVerifyResponse)(nil), "commands.BlindVerifyResponse")
	proto.RegisterType((*GetCredentialRequest)(nil), "commands.GetCredentialRequest")
	proto.RegisterType((*GetCredentialResponse)(nil), "commands.GetCredentialResponse")
	proto.RegisterType((*SpendCredentialRequest)(nil), "commands.SpendCredentialRequest")
	proto.RegisterType((*SpendCredentialResponse)(nil), "commands.SpendCredentialResponse")
	proto.RegisterType((*CredentialPair)(nil), "commands.credentialPair")
	proto.RegisterType((*LookUpCredentialRequest)(nil), "commands.LookUpCredentialRequest")
	proto.RegisterType((*LookUpCredentialResponse)(nil), "commands.LookUpCredentialResponse")
	proto.RegisterType((*LookUpBlockCredentialsRequest)(nil), "commands.LookUpBlockCredentialsRequest")
	proto.RegisterType((*LookUpBlockCredentialsResponse)(nil), "commands.LookUpBlockCredentialsResponse")
}

func init() {
	proto.RegisterFile("common/comm/commands/proto/types.proto", fileDescriptor_c9a06cb57e68cc23)
}

var fileDescriptor_c9a06cb57e68cc23 = []byte{
	// 996 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x41, 0x6f, 0xe3, 0x44,
	0x14, 0xc6, 0x49, 0x93, 0xa6, 0x2f, 0xdd, 0xad, 0x77, 0xda, 0x6d, 0xac, 0x8a, 0xad, 0x8a, 0x85,
	0xa0, 0x45, 0x6c, 0x52, 0x2d, 0x08, 0x24, 0x4e, 0xb8, 0x89, 0xc9, 0x5a, 0x4d, 0x9c, 0x30, 0x76,
	0x0a, 0xcb, 0x25, 0x9a, 0x38, 0xb3, 0x89, 0xa9, 0x63, 0x07, 0x8f, 0x5d, 0xb6, 0x1c, 0xe0, 0x80,
	0xc4, 0x05, 0x09, 0x7e, 0x17, 0xbf, 0x89, 0x0b, 0xf2, 0x78, 0xbc, 0x71, 0x9a, 0xb2, 0xcd, 0xa2,
	0x72, 0x69, 0xfd, 0xde, 0x7c, 0xf3, 0xde, 0xf7, 0x7d, 0xef, 0x45, 0x36, 0x7c, 0xe0, 0x04, 0xb3,
	0x59, 0xe0, 0x37, 0x92, 0x7f, 0xfc, 0x0f, 0xf1, 0xc7, 0xac, 0x31, 0x0f, 0x83, 0x28, 0x68, 0x44,
	0xd7, 0x73, 0xca, 0xea, 0xfc, 0x19, 0x55, 0xb2, 0xb3, 0x83, 0x0f, 0x9d, 0xf0, 0x7a, 0x1e, 0x05,
	0x0d, 0x27, 0x70, 0x02, 0x3f, 0x8e, 0x1a, 0xcc, 0x99, 0xd2, 0x19, 0x5d, 0xbd, 0x72, 0x70, 0x24,
	0x80, 0xd4, 0x9b, 0x90, 0x19, 0xf1, 0x6e, 0x41, 0xd4, 0xdf, 0x58, 0x2a, 0x9e, 0x8d, 0x3c, 0x1a,
	0xe6, 0xf0, 0xea, 0x67, 0x50, 0xb6, 0x22, 0x12, 0xc5, 0x0c, 0x21, 0xd8, 0x70, 0x82, 0x31, 0x55,
	0xa4, 0x23, 0xe9, 0xb8, 0x84, 0xf9, 0x33, 0x52, 0x60, 0x73, 0x46, 0x19, 0x23, 0x13, 0xaa, 0x14,
	0x8e, 0xa4, 0xe3, 0x2d, 0x9c, 0x85, 0xea, 0x7b, 0x50, 0xb5, 0xdc, 0x89, 0x8f, 0xe9, 0x0f, 0x31,
	0x65, 0x51, 0x72, 0x79, 0x1e, 0x8f, 0xba, 0x8a, 0x74, 0x54, 0x3c, 0xde, 0xc6, 0xfc, 0x59, 0xfd,
	0x05, 0xb6, 0x53, 0x08, 0x9b, 0x07, 0x3e, 0xa3, 0xe8, 0x04, 0x8a, 0xcc, 0x9d, 0xf0, 0xfa, 0xd5,
	0x67, 0xb5, 0xba, 0x60, 0x58, 0xef, 0x27, 0x3c, 0x12, 0x20, 0x89, 0xe2, 0x90, 0xe2, 0x04, 0x83,
	0x0e, 0xa0, 0x62, 0x30, 0x16, 0xd3, 0xd0, 0x68, 0xf1, 0xc6, 0x45, 0x5c, 0x71, 0x45, 0x8c, 0x8e,
	0xa1, 0xcc, 0x38, 0x63, 0xa5, 0xc8, 0x2b, 0xc9, 0xf5, 0xcc, 0xc7, 0x7a, 0xaa, 0x04, 0x8b, 0x73,
	0x55, 0x81, 0xfd, 0x0b, 0x1a, 0xba, 0x2f, 0x5d, 0x87, 0x44, 0x6e, 0xe0, 0x9f, 0xd3, 0x6b, 0x41,
	0x57, 0xfd, 0x43, 0x82, 0xda, 0xca, 0x91, 0xa0, 0xf9, 0x14, 0x0a, 0x57, 0x97, 0x82, 0xe5, 0x93,
	0x65, 0x96, 0x37, 0xaf, 0x14, 0xae, 0x2e, 0xef, 0x89, 0xaa, 0x09, 0x0f, 0x78, 0xf1, 0x8c, 0xe1,
	0xdb, 0x98, 0x95, 0x79, 0x5f, 0xc8, 0x79, 0x6f, 0xc3, 0xc3, 0xac, 0x9e, 0x90, 0xa5, 0xc0, 0xa6,
	0xcb, 0x2e, 0x88, 0xe7, 0x8e, 0x79, 0xd1, 0x0a, 0xce, 0xc2, 0x1c, 0xcb, 0xc2, 0x1d, 0x2c, 0x7f,
	0x95, 0x40, 0x3e, 0xf3, 0x5c, 0x7f, 0x7c, 0xc7, 0xe8, 0xd1, 0xc7, 0x50, 0xf6, 0xc8, 0x6c, 0x34,
	0x26, 0xa2, 0xe4, 0xde, 0xb2, 0x80, 0x0e, 0x3f, 0xc3, 0x02, 0x83, 0x9e, 0x42, 0x89, 0x4e, 0xfa,
	0xf1, 0x48, 0xb8, 0x54, 0xab, 0x8b, 0xf5, 0x4e, 0xc1, 0xfd, 0x78, 0xe4, 0xb9, 0x4e, 0x62, 0x77,
	0x8a, 0x52, 0x7f, 0x97, 0xe0, 0x51, 0x8e, 0x85, 0xd0, 0x77, 0x9a, 0x37, 0xec, 0x70, 0xb9, 0x1f,
	0x47, 0xd3, 0xf1, 0xff, 0xb2, 0x64, 0x3f, 0x03, 0xe2, 0xe5, 0xef, 0x73, 0x7c, 0xe8, 0x04, 0x4a,
	0xd1, 0x94, 0x46, 0x44, 0x74, 0xdf, 0x5d, 0x2e, 0x60, 0x27, 0x47, 0x38, 0x45, 0xa8, 0x2f, 0x60,
	0x77, 0xa9, 0xff, 0x3d, 0x8e, 0xfb, 0x6f, 0x09, 0xf6, 0xda, 0x34, 0x6a, 0x86, 0x74, 0x4c, 0xfd,
	0xc8, 0x25, 0x5e, 0xa6, 0xee, 0x5d, 0xd8, 0x9a, 0x67, 0x53, 0xe1, 0xe5, 0xb7, 0xf1, 0x22, 0xb1,
	0x18, 0x67, 0x61, 0x9d, 0x71, 0xe6, 0x76, 0xa5, 0xb8, 0xc6, 0xae, 0xec, 0x41, 0xe9, 0x8a, 0x78,
	0x31, 0x55, 0x36, 0xf8, 0xc4, 0xd2, 0xe0, 0xb5, 0x87, 0xa5, 0x9c, 0x87, 0x7b, 0x50, 0xf2, 0x03,
	0xdf, 0xa1, 0x4a, 0x99, 0x13, 0x4c, 0x03, 0xb4, 0x0f, 0xe5, 0xe8, 0xd5, 0x73, 0xc2, 0xa6, 0xca,
	0x26, 0x4f, 0x8b, 0x08, 0xc9, 0xe9, 0xc0, 0x2a, 0x3c, 0x99, 0x3c, 0xaa, 0x0c, 0x1e, 0xdf, 0x10,
	0xff, 0x9f, 0x37, 0x6d, 0x7d, 0xcb, 0xff, 0x92, 0x60, 0xdf, 0x9a, 0x53, 0x7f, 0xbc, 0x6a, 0xfa,
	0x09, 0x14, 0xad, 0xf5, 0x57, 0xaa, 0x7f, 0x73, 0xa5, 0x4e, 0xa1, 0x64, 0xe7, 0x56, 0xea, 0xe0,
	0x96, 0x95, 0xb2, 0xd3, 0xd7, 0x83, 0xd8, 0xac, 0xc4, 0xc0, 0x8b, 0x55, 0xab, 0x8f, 0x61, 0xa7,
	0x4b, 0x43, 0x67, 0x4a, 0xfc, 0x48, 0x1b, 0x8f, 0x43, 0xca, 0x98, 0x52, 0xe2, 0xa6, 0xed, 0xcc,
	0x96, 0xd3, 0xaa, 0x0b, 0xb5, 0x15, 0x29, 0xc2, 0xc2, 0xf7, 0xe1, 0xc1, 0x8f, 0x84, 0x59, 0xb1,
	0xe3, 0x50, 0xc6, 0x5e, 0xc6, 0x9e, 0xd8, 0xd1, 0xe5, 0xe4, 0x5b, 0xd8, 0xf6, 0x15, 0x3c, 0x74,
	0x5e, 0x77, 0xe9, 0x13, 0x37, 0x4c, 0xc8, 0x4f, 0xc8, 0x6c, 0x46, 0xc4, 0x7a, 0xa6, 0x01, 0x3a,
	0x04, 0x58, 0xe0, 0x78, 0xd5, 0x6d, 0x9c, 0xcb, 0xa8, 0x6d, 0xa8, 0x75, 0x82, 0xe0, 0x72, 0x30,
	0x5f, 0xb5, 0x7f, 0x1f, 0xca, 0x53, 0xea, 0x4e, 0xa6, 0x11, 0xaf, 0x58, 0xc4, 0x22, 0x5a, 0x34,
	0x2a, 0xe4, 0x1a, 0xa9, 0xbf, 0x49, 0xa0, 0xac, 0x56, 0x12, 0xea, 0xbf, 0xbc, 0xc9, 0x56, 0x0c,
	0x55, 0x59, 0xe8, 0x5b, 0x3e, 0xc7, 0x37, 0xd5, 0xad, 0xef, 0xcc, 0xe7, 0xf0, 0x24, 0xe5, 0x71,
	0xe6, 0x05, 0xce, 0xe5, 0x82, 0x0c, 0xbb, 0x43, 0x57, 0xa2, 0xe0, 0xf0, 0xdf, 0x6e, 0x0a, 0x1d,
	0x5f, 0x40, 0x75, 0xc1, 0x8b, 0xf1, 0x17, 0xc0, 0x9b, 0x44, 0xe4, 0xc1, 0xeb, 0x2b, 0xf8, 0xe8,
	0xcf, 0x02, 0x40, 0x9a, 0x6a, 0x26, 0x9f, 0x24, 0x65, 0x28, 0xf4, 0xce, 0xe5, 0x77, 0x50, 0x15,
	0x36, 0x07, 0xe6, 0xb9, 0xd9, 0xfb, 0xc6, 0x94, 0x25, 0xb4, 0x0b, 0x3b, 0x86, 0x79, 0xa1, 0x75,
	0x8c, 0xd6, 0xb0, 0xd9, 0xeb, 0x76, 0x35, 0xb3, 0x25, 0x17, 0xd0, 0x63, 0x78, 0x94, 0x25, 0x35,
	0xdc, 0x1e, 0x74, 0x75, 0xd3, 0xb6, 0xe4, 0x22, 0xda, 0x03, 0xb9, 0x8f, 0x7b, 0x4d, 0xdd, 0xb2,
	0x0c, 0xb3, 0x3d, 0xd4, 0x31, 0xee, 0x61, 0x79, 0x23, 0xa9, 0x60, 0xf6, 0xec, 0xa1, 0xd1, 0xed,
	0x77, 0xf4, 0x04, 0xa9, 0xb7, 0xe4, 0x52, 0x92, 0xc4, 0xfa, 0xd7, 0x03, 0xdd, 0xb2, 0x87, 0xb6,
	0xd1, 0xd5, 0x7b, 0x03, 0x5b, 0x2e, 0xa3, 0x1d, 0xa8, 0x0e, 0x4c, 0xed, 0x42, 0x33, 0x3a, 0xda,
	0x59, 0x47, 0x97, 0x37, 0x51, 0x0d, 0x76, 0xb3, 0x3e, 0x36, 0xd6, 0x4c, 0x4b, 0x6b, 0xda, 0x46,
	0xcf, 0x94, 0x2b, 0x79, 0x56, 0x67, 0x86, 0xd9, 0x32, 0xcc, 0xb6, 0xbc, 0x95, 0x67, 0x65, 0x19,
	0x6d, 0x53, 0xb3, 0x07, 0x58, 0x97, 0x21, 0xc1, 0xda, 0xdf, 0x0e, 0x13, 0x0a, 0x3d, 0x73, 0xd8,
	0x7c, 0xae, 0x19, 0xa6, 0x5c, 0x4d, 0xb0, 0x49, 0x46, 0xd0, 0xd5, 0x5b, 0xc3, 0x17, 0xba, 0x2d,
	0x6f, 0x9f, 0x7d, 0xfa, 0xdd, 0xb3, 0xd3, 0x57, 0xc4, 0x21, 0xa3, 0x7a, 0x10, 0x4e, 0x1a, 0xdf,
	0xb3, 0x28, 0x76, 0x7e, 0xba, 0xf6, 0x1b, 0xcd, 0xf4, 0x07, 0xdd, 0x0e, 0x1a, 0xb7, 0x7d, 0x80,
	0x8e, 0xca, 0xfc, 0x83, 0xef, 0x93, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x78, 0x60, 0xdc, 0x92,
	0x9f, 0x0a, 0x00, 0x00,
}
