// Code generated by queueGen; DO NOT EDIT.

// requestqueue_queueGen.go - Queue implementation for putting seemingly infinite number of CommandRequests onto a channel.
// Copyright (C) 2019-2019  Jedrzej Stuczynski.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Package requestqueue is implemented based on eapache's infinite channel template:
// https://github.com/eapache/channels/blob/master/infinite_channel.go
// As explained by the author in documentation: https://godoc.org/github.com/eapache/channels due to Go's type system
// limitations direct import of his library is impractical.
// This reimplementation allows more type safety due to having more strict channel type than an empty interface.
// On top of better, even though slightly slower, queue as now it is thread-safe which is crucial as the queue
// can be read by multiple workers.
package requestqueue

import (
	"fmt"

	"0xacab.org/jstuczyn/CoconutGo/server/commands"
	"github.com/Workiva/go-datastructures/queue"
)

// minQueueLen is the smallest capacity that queue may have.
const minQueueLen = 16

// RequestQueue represents a seemingly 'infinite' (depending on available memory) FIFO queue working on CommandRequest items.
type RequestQueue struct {
	input  chan *commands.CommandRequest
	output chan *commands.CommandRequest
	length chan int64
	buffer *queue.Queue
}

// In returns input channel for writing CommandRequests.
func (ic *RequestQueue) In() chan<- *commands.CommandRequest {
	return ic.input
}

// Out returns output channel for reading CommandRequests.
func (ic *RequestQueue) Out() <-chan *commands.CommandRequest {
	return ic.output
}

// Len returns number of elements in the queue.
func (ic *RequestQueue) Len() int64 {
	return <-ic.length
}

// Close closes the input channel, however, output and hence the goroutine will be open until the queue is exhausted.
func (ic *RequestQueue) Close() {
	close(ic.input)
}

func (ic *RequestQueue) infiniteBuffer() {
	var input, output chan *commands.CommandRequest
	var next *commands.CommandRequest
	input = ic.input

	for input != nil || output != nil {
		select {
		case elem, open := <-input:
			if open {
				err := ic.buffer.Put(elem)
				if err != nil {
					// there is nothing more we can do,
					// if we don't panic, all workers will block trying to read/write to closed channels.
					// Moreover the error should never be returned during normal operations.
					panic(fmt.Sprintf("The RequestQueue is in invalid state: %v", err))
				}
			} else {
				input = nil
			}
		case output <- next:
			_, err := ic.buffer.Get(1)
			// same rationale as with previous panics
			if err != nil {
				panic(fmt.Sprintf("The RequestQueue is in invalid state: %v", err))
			}
		case ic.length <- ic.buffer.Len():
		}

		if ic.buffer.Len() > 0 {
			output = ic.output
			nextT, err := ic.buffer.Peek()

			if err != nil {
				// Error can only happen if either the queue is already disposed what similarly to input should have
				// never happened accidentally and then there's nothing we can really do or if there are no items in the
				// queue which is also impossible due to explicit check.
				panic(fmt.Sprintf("The RequestQueue is in invalid state: %v", err))
			}
			next = nextT.(*commands.CommandRequest)

		} else {
			output = nil
			next = nil
		}
	}

	close(ic.output)
	close(ic.length)
}

// New creates a new instance of a RequestQueue.
func New() *RequestQueue {
	ic := &RequestQueue{
		input:  make(chan *commands.CommandRequest),
		output: make(chan *commands.CommandRequest),
		length: make(chan int64),
		buffer: queue.New(minQueueLen),
	}

	go ic.infiniteBuffer()
	return ic
}
