// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/comm/grpc/proto/services.proto

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	commands "github.com/jstuczyn/CoconutGo/server/commands"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DummyRequest struct {
	Hello                string   `protobuf:"bytes,1,opt,name=hello,proto3" json:"hello,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DummyRequest) Reset()         { *m = DummyRequest{} }
func (m *DummyRequest) String() string { return proto.CompactTextString(m) }
func (*DummyRequest) ProtoMessage()    {}
func (*DummyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2b6eb38364b0bff, []int{0}
}

func (m *DummyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DummyRequest.Unmarshal(m, b)
}
func (m *DummyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DummyRequest.Marshal(b, m, deterministic)
}
func (m *DummyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DummyRequest.Merge(m, src)
}
func (m *DummyRequest) XXX_Size() int {
	return xxx_messageInfo_DummyRequest.Size(m)
}
func (m *DummyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DummyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DummyRequest proto.InternalMessageInfo

func (m *DummyRequest) GetHello() string {
	if m != nil {
		return m.Hello
	}
	return ""
}

type DummyResponse struct {
	Echo                 string   `protobuf:"bytes,1,opt,name=echo,proto3" json:"echo,omitempty"`
	World                string   `protobuf:"bytes,2,opt,name=world,proto3" json:"world,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DummyResponse) Reset()         { *m = DummyResponse{} }
func (m *DummyResponse) String() string { return proto.CompactTextString(m) }
func (*DummyResponse) ProtoMessage()    {}
func (*DummyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2b6eb38364b0bff, []int{1}
}

func (m *DummyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DummyResponse.Unmarshal(m, b)
}
func (m *DummyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DummyResponse.Marshal(b, m, deterministic)
}
func (m *DummyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DummyResponse.Merge(m, src)
}
func (m *DummyResponse) XXX_Size() int {
	return xxx_messageInfo_DummyResponse.Size(m)
}
func (m *DummyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DummyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DummyResponse proto.InternalMessageInfo

func (m *DummyResponse) GetEcho() string {
	if m != nil {
		return m.Echo
	}
	return ""
}

func (m *DummyResponse) GetWorld() string {
	if m != nil {
		return m.World
	}
	return ""
}

func init() {
	proto.RegisterType((*DummyRequest)(nil), "services.dummyRequest")
	proto.RegisterType((*DummyResponse)(nil), "services.dummyResponse")
}

func init() {
	proto.RegisterFile("server/comm/grpc/proto/services.proto", fileDescriptor_e2b6eb38364b0bff)
}

var fileDescriptor_e2b6eb38364b0bff = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4b, 0x4b, 0xc4, 0x30,
	0x14, 0x85, 0xa9, 0xe8, 0x30, 0x06, 0x15, 0x0c, 0x3e, 0xca, 0xac, 0x66, 0x06, 0x05, 0x57, 0x0d,
	0x8c, 0x0b, 0x99, 0x95, 0xe8, 0x80, 0x83, 0xb8, 0x91, 0x0a, 0x82, 0xee, 0xda, 0xf4, 0xda, 0x46,
	0xda, 0xa4, 0x26, 0x37, 0x23, 0xf5, 0xf7, 0xf8, 0x43, 0xa5, 0x8f, 0xf8, 0xa8, 0x30, 0xbb, 0x9c,
	0x7b, 0xbf, 0x73, 0x73, 0xe0, 0x90, 0x53, 0x03, 0x7a, 0x05, 0x9a, 0x71, 0x55, 0x14, 0x2c, 0xd5,
	0x25, 0x67, 0xa5, 0x56, 0xa8, 0x58, 0x3d, 0x16, 0x1c, 0x4c, 0xd0, 0x48, 0x3a, 0x74, 0x7a, 0x34,
	0xf9, 0x65, 0x88, 0x64, 0x62, 0x3a, 0x1e, 0xab, 0xd2, 0xc1, 0xd3, 0x13, 0xb2, 0x93, 0xd8, 0xa2,
	0xa8, 0x42, 0x78, 0xb3, 0x60, 0x90, 0x1e, 0x90, 0xad, 0x0c, 0xf2, 0x5c, 0xf9, 0xde, 0xd8, 0x3b,
	0xdb, 0x0e, 0x5b, 0x31, 0x9d, 0x93, 0xdd, 0x8e, 0x32, 0xa5, 0x92, 0x06, 0x28, 0x25, 0x9b, 0xc0,
	0x33, 0x47, 0x35, 0xef, 0xda, 0xfa, 0xae, 0x74, 0x9e, 0xf8, 0x1b, 0xad, 0xb5, 0x11, 0xb3, 0x4f,
	0x8f, 0x0c, 0x6e, 0x8d, 0xb1, 0xa0, 0xe9, 0x13, 0xa1, 0x4b, 0xc0, 0x47, 0xd0, 0xe2, 0x45, 0xf0,
	0x08, 0x85, 0x92, 0x77, 0x50, 0xd1, 0x71, 0xe0, 0xe2, 0x05, 0xbd, 0x55, 0x97, 0x69, 0x34, 0x59,
	0x43, 0x74, 0x79, 0x2e, 0xc9, 0xde, 0x83, 0x48, 0xe5, 0x15, 0xa2, 0x16, 0xb1, 0x45, 0x30, 0xf4,
	0xf0, 0xc7, 0x54, 0x6f, 0xdc, 0xad, 0xa3, 0xfe, 0xb8, 0x3d, 0x30, 0x0b, 0xc9, 0xf0, 0x5e, 0xab,
	0x95, 0x48, 0x40, 0xd3, 0x1b, 0xb2, 0xdf, 0xfc, 0x53, 0x2d, 0x34, 0x24, 0x20, 0x51, 0x44, 0xb9,
	0xa1, 0xc7, 0xbd, 0x10, 0xdf, 0xe9, 0xfc, 0xff, 0x8b, 0xf6, 0xe6, 0xf5, 0xfc, 0xf9, 0x22, 0x15,
	0x98, 0xd9, 0xb8, 0x26, 0xd8, 0xab, 0x41, 0xcb, 0x3f, 0x2a, 0xc9, 0x16, 0x8a, 0x2b, 0x69, 0x71,
	0xd9, 0x16, 0xf7, 0xa7, 0x4f, 0xd7, 0x5c, 0x3c, 0x68, 0xda, 0x39, 0xff, 0x0a, 0x00, 0x00, 0xff,
	0xff, 0x6f, 0xd7, 0x01, 0x29, 0xf3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IssuerClient is the client API for Issuer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IssuerClient interface {
	GetVerificationKey(ctx context.Context, in *commands.VerificationKeyRequest, opts ...grpc.CallOption) (*commands.VerificationKeyResponse, error)
	SignAttributes(ctx context.Context, in *commands.SignRequest, opts ...grpc.CallOption) (*commands.SignResponse, error)
}

type issuerClient struct {
	cc *grpc.ClientConn
}

func NewIssuerClient(cc *grpc.ClientConn) IssuerClient {
	return &issuerClient{cc}
}

func (c *issuerClient) GetVerificationKey(ctx context.Context, in *commands.VerificationKeyRequest, opts ...grpc.CallOption) (*commands.VerificationKeyResponse, error) {
	out := new(commands.VerificationKeyResponse)
	err := c.cc.Invoke(ctx, "/services.Issuer/GetVerificationKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issuerClient) SignAttributes(ctx context.Context, in *commands.SignRequest, opts ...grpc.CallOption) (*commands.SignResponse, error) {
	out := new(commands.SignResponse)
	err := c.cc.Invoke(ctx, "/services.Issuer/SignAttributes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IssuerServer is the server API for Issuer service.
type IssuerServer interface {
	GetVerificationKey(context.Context, *commands.VerificationKeyRequest) (*commands.VerificationKeyResponse, error)
	SignAttributes(context.Context, *commands.SignRequest) (*commands.SignResponse, error)
}

func RegisterIssuerServer(s *grpc.Server, srv IssuerServer) {
	s.RegisterService(&_Issuer_serviceDesc, srv)
}

func _Issuer_GetVerificationKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commands.VerificationKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServer).GetVerificationKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.Issuer/GetVerificationKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServer).GetVerificationKey(ctx, req.(*commands.VerificationKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Issuer_SignAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commands.SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServer).SignAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.Issuer/SignAttributes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServer).SignAttributes(ctx, req.(*commands.SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Issuer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.Issuer",
	HandlerType: (*IssuerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVerificationKey",
			Handler:    _Issuer_GetVerificationKey_Handler,
		},
		{
			MethodName: "SignAttributes",
			Handler:    _Issuer_SignAttributes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/comm/grpc/proto/services.proto",
}

// ProviderClient is the client API for Provider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProviderClient interface {
	VerifyCredentials(ctx context.Context, in *commands.VerifyRequest, opts ...grpc.CallOption) (*commands.VerifyResponse, error)
}

type providerClient struct {
	cc *grpc.ClientConn
}

func NewProviderClient(cc *grpc.ClientConn) ProviderClient {
	return &providerClient{cc}
}

func (c *providerClient) VerifyCredentials(ctx context.Context, in *commands.VerifyRequest, opts ...grpc.CallOption) (*commands.VerifyResponse, error) {
	out := new(commands.VerifyResponse)
	err := c.cc.Invoke(ctx, "/services.Provider/VerifyCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderServer is the server API for Provider service.
type ProviderServer interface {
	VerifyCredentials(context.Context, *commands.VerifyRequest) (*commands.VerifyResponse, error)
}

func RegisterProviderServer(s *grpc.Server, srv ProviderServer) {
	s.RegisterService(&_Provider_serviceDesc, srv)
}

func _Provider_VerifyCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commands.VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).VerifyCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.Provider/VerifyCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).VerifyCredentials(ctx, req.(*commands.VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Provider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.Provider",
	HandlerType: (*ProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyCredentials",
			Handler:    _Provider_VerifyCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/comm/grpc/proto/services.proto",
}
